default: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  schema_search_path: public, postgis

development:
  <<: *default
  database: productiveness_development

test:
  <<: *default
  database: productiveness_test

production:
  url: <%= ENV['DATABASE_URL'].sub(/^postgres/, "postgis") %>
